#!/usr/bin/env bash
# Installs git hooks to automatically run .ai/sync/sync.sh on checkout and merge.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../" && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"

# Ensure hooks directory exists
if [[ ! -d "$HOOKS_DIR" ]]; then
    echo "Error: .git/hooks directory not found. Are you in a git repository?"
    exit 1
fi

HOOK_SCRIPT="#!/bin/sh
# Auto-generated by .ai/sync/setup_hooks.sh
# Syncs AI configs after a merge or checkout to ensure local tools are up to date.

if [ -f \".ai/sync/sync.sh\" ]; then
    echo \"Running AI Config Sync...\"
    .ai/sync/sync.sh
fi
"

# Install post-merge hook
echo "$HOOK_SCRIPT" > "$HOOKS_DIR/post-merge"
chmod +x "$HOOKS_DIR/post-merge"
echo "Installed post-merge hook."

# Install post-checkout hook
echo "$HOOK_SCRIPT" > "$HOOKS_DIR/post-checkout"
chmod +x "$HOOKS_DIR/post-checkout"
echo "Installed post-checkout hook."

echo "Git hooks installed successfully! AI configs will now sync automatically on pull/checkout."
